### ISSUE TITLE
Remove "end of" comments when the end statement has the procedure name, and remove return statements just before procedure ends.

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fortran-lapack#10]
The end of the function stdlib_dasum in https://github.com/perazz/fortran-lapack/blob/main/src/stdlib_linalg_blas_d.f90 looks like

```
           return
           ! end of stdlib_dasum
     end function stdlib_dasum
```
with similar lines for other procedures. If the last line of the function were just `end` the comment would inform the reader which procedure is being terminated, but since the procedure name is listed in `end function stdlib_dasum` the comment is redundant and can be removed. Also a `return` that is just before the end of a procedure is redundant and can be removed.

**Comment by perazz** [comment]
Thank you @Beliavsky, fixed by #21.
