### ISSUE TITLE
Formatting: remove multiple consecutive blank lines

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fortran-lapack#3]
I think code is more readable when there are not too many blank lines, so that you can see more of it on your screen. I suggest that multiple consecutive blank lines, for example found at https://github.com/perazz/fortran-lapack/blob/main/src/stdlib_linalg_blas_d.f90 , be replaced by a single blank line.

**Comment by perazz** [comment]
Thanks, I will close this as I've introduced `fprettify` in the pipeline, still improvable though.
