### ISSUE TITLE
Define constants at module level

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fortran-lapack#6]
At https://github.com/perazz/fortran-lapack/blob/main/src/stdlib_linalg_blas_d.f90 the lines of code

```
           real(dp) :: one, zero
           parameter(one=1.0_dp, zero=0.0_dp)
```
appear in many procedures. Instead define private named constants

`real(dp), parameter :: one=1.0_dp, zero=0.0_dp`

before the contains statement. In a few places 

`real(dp), parameter :: dzero = 0.0_dp`

appears. I think `dzero` can be replaced with `zero` once it is made a module-level constant.

**Comment by perazz** [comment]
Great suggestion! Completed between https://github.com/perazz/fortran-lapack/compare/1658134...b297a60
