### ISSUE TITLE
Avoid the use of double precision function dabs and dble

### ISSUE THREAD

**Issue by Beliavsky** [perazz/fortran-lapack#8]
Instead of `dabs(x)` write `real(x, kind=dp)` and instead of `dble(i)` write `real(i, kind=dp)`. Ideally the code should be written so that it still works if dp is set to a quadruple precision kind.

**Comment by perazz** [comment]
fixed-precision constants "`.d0`" are also still hanging around: 

https://github.com/perazz/fortran-lapack/blob/f8b0ed1f89e485fed7302e27d9f57d736a2fe7f3/src/stdlib_linalg_blas_d.f90#L1183-L1184
